# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'

target 'ExampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FBMemoryProfiler
  pod 'FBMemoryProfiler'#, :path=>'../'
  pod 'FBRetainCycleDetector', '~> 1.0'
  pod 'FBAllocationTracker'

end
